# Generated by Django 4.1.2 on 2022-10-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalcHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibd', models.CharField(max_length=200)),
                ('val1', models.CharField(max_length=50)),
                ('val2', models.CharField(max_length=50)),
                ('operator', models.DateTimeField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField()),
            ],
        ),
    ]
